Recipe.create(title: 'adsf', level: 'asd', category: 'fasd', resources: 'fads', ingredients: 'fads', servings: 'fads')
Recipe.create(title: 'pizza', level: 3, category: 'meat', resources: 'pan bowl', ingredients: 'cheese sauce dough', servings: 5)
Recipe.create(title: 'asdf', level: 'hello', category: 'yes', resources: 'no', ingredients: 'asdf', servings: 4)
Recipe.create(title: 'coffee', level: 11, category: 'drink', resources: 'cup', ingredients: 'coffee grounds', servings: 1)
Recipe.create(title: 'pizza', level: 'test', category: 'why', resources: 'me', ingredients: 'ok', servings: 4)
Recipe.create(title: 'meatballs', level: 4, category: 'meat', resources: 'pan', ingredients: 'meat', servings: 6)
Recipe.create(title: 'sdf', level: 'asdfa', category: 'dasd', resources: 'asdf', ingredients: 'asfasd', servings: 'fasd')
Recipe.create(title: 'wine', level: 20, category: 'spirts', resources: 'cup', ingredients: 'wine', servings: 2)
Recipe.create(title: 'why', level: 'hello', category: 'there', ingredients: 'fine', servings: 'bye')
Recipe.create(title: 'ok', level: 'hello', category: 'whatever', ingredients: 'blah', servings: 'yeah')
Recipe.create(title: '', level: '', category: '', resources: '', ingredients: '', servings: '')
Recipe.create(title: 'chips', level: 2, category: 'snack', resources: 'none', ingredients: 'chips', servings: 1)
Recipe.create(title: 'hello', level: 'world', category: 'ok', resources: 'still', ingredients: 'going', servings: 'strong')
