Recipe.create(title: 'adsf', level: 'asd', category: 'fasd', resources: 'fads', ingredients: 'fads', servings: 'fads')
Recipe.create(title: 'pizza', level: 3, category: 'meat', resources: 'pan bowl', ingredients: 'cheese sauce dough', servings: 5)
Recipe.create(title: 'asdf', level: 'hello', category: 'yes', resources: 'no', ingredients: 'asdf', servings: 4)
Recipe.create(title: 'coffee', level: 11, category: 'drink', resources: 'cup', ingredients: 'coffee grounds', servings: 1)
Recipe.create(title: 'pizza', level: 'test', category: 'why', resources: 'me', ingredients: 'ok', servings: 4)
Recipe.create(title: 'meatballs', level: 4, category: 'meat', resources: 'pan', ingredients: 'meat', servings: 6)
Recipe.create(title: 'sdf', level: 'asdfa', category: 'dasd', resources: 'asdf', ingredients: 'asfasd', servings: 'fasd')
Recipe.create(title: 'wine', level: 20, category: 'spirts', resources: 'cup', ingredients: 'wine', servings: 2)
Recipe.create(title: 'why', level: 'hello', category: 'there', ingredients: 'fine', servings: 'bye')
Recipe.create(title: 'ok', level: 'hello', category: 'whatever', ingredients: 'blah', servings: 'yeah')
Recipe.create(title: '', level: '', category: '', resources: '', ingredients: '', servings: '')
Recipe.create(title: 'chips', level: 2, category: 'snack', resources: 'none', ingredients: 'chips', servings: 1)
Recipe.create(title: 'hello', level: 'world', category: 'ok', resources: 'still', ingredients: 'going', servings: 'strong')
Recipe.create(title: vitae, level: 30, category: magna, resources: volutpat, ingredients: tristique,, servings: 99)
Recipe.create(title: sapien, level: 91, category: dapibus, resources: volutpat, ingredients: ipsum, servings: 13, title: in, level: 32, category: Curabitur, resources: congue., ingredients: lectus, servings: 25, title: magna, level: 22, category: dolor, resources: Aenean, ingredients: sodales, servings: 2, title: at., level: 62, category: congue, resources: augue, ingredients: Duis, servings: 0, title: faucibus, level: 0, category: ut, resources: mauris, ingredients: nibh., servings: 4, title: vel, level: 34, category: sodales, resources: ultrices, ingredients: at, servings: 82, title: Morbi, level: 18, category: congue., resources: at, ingredients: ipsum, servings: 88, title: Aenean, level: 20, category: ultricies,, resources: risus., ingredients: dolor, servings: 8, title: sapien, level: 68, category: elit, resources: dictum, ingredients: euismod, servings: 13, title: in, level: 50, category: at., resources: sapien, ingredients: congue, servings: 67)
